name: Push to DockerHub

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: fetch submodule tags
        run: |
          cd Xray-core
          git fetch --prune --unshallow --tags
          cd ..
      - name: Checkout latest tag of submodule
        run: |
          git submodule foreach 'echo $name : `git describe --tags`'
          git submodule foreach 'git checkout $(git describe --tags)'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sievelau/xray-core:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
  
