name: Push to DockerHub

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Checkout latest tag of submodule
        run: |
          ls -alh ./

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Test
        run: go test -timeout 1h -v Xray-core/...
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOEKN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: sievelau/mosdns:latest
    
  
